# Generated by Django 5.2.4 on 2025-08-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_chatbot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('user_input', 'User Input'), ('message', 'Message'), ('branch', 'Branch'), ('end', 'End'), ('send_msg_with_options', 'Send Msg with Options'), ('send_image', 'Send Image'), ('file_upload', 'File Upload')], max_length=32),
        ),
    ]
