# Generated by Django 5.2.4 on 2025-08-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_node_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('user_input', 'User Input'), ('message', 'Message'), ('branch', 'Branch'), ('end', 'End')], max_length=32),
        ),
    ]
