# Generated by Django 5.2.4 on 2025-08-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_alter_node_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chatbot_files/'),
        ),
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot_images/'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('user_input', 'User Input'), ('message', 'Message'), ('image', 'Image'), ('file_upload', 'File Upload'), ('branch', 'Branch'), ('end', 'End')], max_length=32),
        ),
    ]
