# Generated by Django 5.2.4 on 2025-09-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_node_file_node_image_alter_node_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='uploaded_files/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='builder.chatbot')),
            ],
        ),
    ]
